# Simple package

name: ks
parent: default

matches:
  - trigger: "öok"
    replace: |
      Guten Tag {{Name}}

      Gib mir doch bitte eine kurze Rückbestätigung, dass Du mit der Reservation und den Bedingungen einverstanden bist.

      Bei Fragen stehe ich gerne zur Verfügung.

      Freundliche Grüsse
      {{user-firstname}}

  - trigger: "ödank"
    replace: |
      Guten Tag {{Name}}

      Super, besten Dank für die Bestätigung.

      Bei Fragen stehe ich gerne zur Verfügung.

      Freundliche Grüsse
      {{user-firstname}}
