matches:

  - trigger: ",rs"
    replace: "rentshop®"

  - trigger: ",specs"
    form: |
      ### [[Titel hier einfügen]]

      [[Beschreibung hier einfügen]]

      [SpecificationsStart]

      • 

      [SpecificationsEnd]
