matches:
  - trigger: ":specs"
    form: |
      ### [[title]]

      [[beschreibung]]

      __**Technische Daten**__  
      [SpecificationsStart]

      • 

      [SpecificationsEnd]
    vars:
      - name: title
        type: text
        default: "Titel hier einfügen"
      - name: beschreibung
        type: text
        default: "Beschreibung hier einfügen"
