matches:

  - trigger: ",rs"
    replace: "rentshop®"

  - trigger: ",specs"
    replace: |
      ### {{Titel hier einfügen}}

      {{Beschreibung hier einfügen}}

      __**Technische Daten**__  
      [SpecificationsStart]

      • 

      [SpecificationsEnd]
