imports:
  - "sub/_tawk.yml"
  - "sub/_generator.yml"
  - "sub/_struggler.yml"

matches:

  - trigger: ",doppel"
    form: |
      Guten Tag [[Name]]

      ​Wie wir feststellen mussten, wurde die Rechnung im Anhang zweimal überwiesen.
      Damit wir die Zahlung zurückerstatten können, benötigen wir noch Deine IBAN.

      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",fdoppel"
    form: |
      Bonjour [[Name]]  
      
      Nous avons constaté que la facture jointe a été versée deux fois.
      Afin que nous puissions rembourser le paiement, nous avons besoin de votre IBAN.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",iban"
    form: |
      Unser Kontoangaben lauten wie folgt:

      meisterwerk GmbH
      Dorf 10
      3053 Deisswil
      Zürcher Kantonalbank
      IBAN: CH35 0070 0110 0049 6385 9
      SWIFT (BIC): ZKBKCHZZ80A

  - trigger: ",fiban"
    form: |
      Nos coordonnées bancaires sont les suivantes:

      meisterwerk GmbH
      Dorf 10
      3053 Deisswil
      Zürcher Kantonalbank
      IBAN: CH35 0070 0110 0049 6385 9
      SWIFT (BIC): ZKBKCHZZ80A

  - trigger: ",anvo"
    form: |
      Guten Tag [[Name]] 

      Da die Vorkassenrechnung bis heute nicht beglichen wurde, wird die Bestellung nun storniert.
      Wir hoffen ein anderes Mal behilflich sein zu können.

      Bei Fragen stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",fanvo"
    form: |
      Bonjour [[Name]]  
      
      Comme la facture de prépaiement n'a pas été réglée à ce jour, la commande est maintenant annulée.
      Nous espérons pouvoir vous aider une autre fois.

      Je reste à votre disposition pour toute question.
      
      Meilleures salutations
      {{firstname}}
  
  - trigger: ",rüdep"
    form: |
      Guten Tag [[Name]]  
      
      Deine Buchung ist zurückgekommen - besten Dank.
      Damit wir das Depot zurückerstatten können, benötigen wir noch Deine IBAN.
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",früdep"
    form: |
      Bonjour [[Name]]  
      
      Votre commande est de retour - merci beaucoup.
      Afin que nous puissions rembourser le dépôt, nous avons besoin de votre IBAN.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",fg"
    replace: |
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",ffg"
    replace: |
      Meilleures salutations
      {{firstname}}
      
  - trigger: ",ruck"
    form: |
      Guten Tag [[Name]]  
      
      Besten Dank für die Rückmeldung.

  - trigger: ",fruck"
    form: |
      Bonjour [[Name]]  
      
      Merci pour votre réponse.

  - trigger: ",anf"
    replace: "Guten Tag Besten Dank für die Anfrage."
    
  - trigger: ",fanf"
    replace: "Bonjour Nous vous remercions pour votre demande."

  - trigger: ",handy"
    replace: "Damit ich den Mietvertrag zustellen kann, benötige ich noch eine schweizer Handynummer. Der Mietvertrag wird per SMS Code unterschrieben."

  - trigger: ",fhandy"
    replace: "Pour pouvoir envoyer le contrat de location, j'ai besoin d'un numéro de téléphone portable suisse. Le contrat de location sera signé par un code SMS."

  - trigger: ",depot"
    replace: "Bitte beachte, dass während der Miete ein Depot hinterlegt werden muss."
    
  - trigger: ",fdepot"
    replace: "Veuillez noter qu'un dépôt de garantie doit être versé pendant la location."
    
  - trigger: ",track"
    form: "http://www.post.ch/swisspost-tracking?formattedParcelCodes=99.60.096403.0000[[Nummer]]&p_language=de"   
        
  - trigger: ",ftrack"
    form: "http://www.post.ch/swisspost-tracking?formattedParcelCodes=99.60.096403.0000[[Nummer]]&p_language=fr"
    
  - trigger: ",fehlt"
    replace: "Für die Bestätigung der Offerte, benötige ich noch Deine Adresse und die Natelnummer."
        
  - trigger: ",ffehlt"
    replace: "Pour la confirmation de l'offre, j'ai besoin de votre adresse et de votre numéro de téléphone portable."
    
  - trigger: ",ofer"
    replace: "Damit ich dir eine Offerte zustellen kann, benötige ich noch Deinen Namen, Adresse, Natelnummer und E-Mail Adresse."
        
  - trigger: ",fofer"
    replace: "Pour que je puisse vous envoyer une offre, j'ai besoin de votre nom, adresse, numéro de téléphone portable et adresse e-mail."
    
  - trigger: ",frag"
    replace: "Bei Fragen oder Änderungswünschen stehe ich gerne zur Verfügung."    
        
  - trigger: ",ffrag"
    replace: "Je suis à votre disposition pour toute question ou demande de modification."  
    
  - trigger: ",lagzh"
    replace: "Das Lager Zürich hat unter der Woche täglich von 10.00 -17.00 Uhr geöffnet. Am Donnerstag kann auf Anfrage bis um 19.00 Uhr abgeholt werden."

  - trigger: ",flagzh"
    replace: "L'entrepôt de Zurich est ouvert tous les jours de la semaine de 10h00 à 17h00. Le jeudi, il est possible de venir chercher les articles jusqu'à 19h00 sur demande."
    
  - trigger: ",lagbs"
    replace: "Das Lager Basel hat jeweils am Mittwoch von 18:00 - 19:30 Uhr geöffnet."  

  - trigger: ",flagbs"
    replace: "L'entrepôt de Bâle est ouvert le mercredi de 18h00 à 19h30."  
    
  - trigger: ",lagbe"
    replace: "Das Lager Bern hat jeweils am Mittwoch von 17:00-19:00 Uhr geöffnet. Falls Dir die Zeiten nicht passen, haben wir in Bern auch ein Pickup Lager (ohne Betreuung), bei welchem Du jederzeit dein Equipment abholen und returnieren kannst. Bitte lass mich es wissen, falls Du lieber auf Pickup wechseln möchtest."
    
  - trigger: ",flagbe"
    replace: "L'entrepôt de Berne est ouvert le mercredi de 17h00 à 19h00. Si ces horaires ne vous conviennent pas, nous avons également un entrepôt pickup (sans personnel d'accueil) à Berne, où vous pouvez venir chercher votre équipement et le retourner à tout moment. Merci de me prévenir si vous préférez passer au pickup."

  - trigger: ",ok"
    form: |
      Guten Tag [[Name]]
      
      Ich wollte kurz nachfragen, ob Du die Bestätigung schon anschauen konntest. 
      Gib mir doch bitte eine kurze Rückbestätigung, dass Du mit der Reservation und den Bedingungen einverstanden bist.
      
      Bei Fragen stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",fok"
    form: |
      Bonjour [[Name]]
      
      Je voulais vous demander si vous aviez déjà pu jeter un coup d'œil à la confirmation. 
      Je vous invite à me confirmer brièvement que vous êtes d'accord avec la réservation et les conditions.
      
      Je suis à votre disposition pour toute question.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",dank"
    form: |
      Guten Tag [[Name]]  
      
      Super, besten Dank für die Bestätigung.  
      
      Bei Fragen stehe ich gerne zur Verfügung.  
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",fdank"
    form: |
      Bonjour [[Name]]  
      
      Super, merci beaucoup pour la confirmation.  
      
      Je suis à votre disposition pour toute question.  
      
      Meilleures salutations
      {{firstname}}
  
  - trigger: ",vert"
    form: |
      Guten Tag [[Name]]  
      
      Ich wollte kurz nachfragen, ob Du den Mietvertrag (E-Mail von e-Signature) schon anschauen konntest.
      
      Falls es diesbezüglich Unklarheiten oder Änderungswünsche gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
  
  - trigger: ",fvert"
    form: |
      Bonjour [[Name]]  
      
      Je voulais vous demander si vous aviez déjà pu consulter le contrat de location (e-mail d'e-Signature).
      
      S'il y a des imprécisions ou des demandes de modification à ce sujet, je serai ravi*e de vous aider.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",dring"
    form: |
      Guten Tag [[Name]]  

      Besten Dank für die Anfrage.
      Ich habe soeben den Mietvertrag zugestellt (siehe E-Mail von e-Signature). 
      Bitte sende uns den Vertrag vor 14.00 Uhr zurück, damit wir die Ware noch heute versenden können.
      
      Falls es diesbezüglich Unklarheiten oder Änderungswünsche gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
        
  - trigger: ",fdring"
    form: |
      Bonjour [[Name]] 
      
      Merci pour votre demande.
      Je viens de vous envoyer le contrat de location (voir e-mail d'e-Signature). 
      Merci de nous renvoyer le contrat avant 14h00 afin que nous puissions envoyer la marchandise à temps.
      
      S'il y a des ambiguïtés ou des modifications à ce sujet, je serai ravi*e de vous aider.
      
      Meilleures salutations 
      {{firstname}}

  - trigger: ",drafol"
    form: |
      Guten Tag [[Name]]  
      
      Ich wollte kurz nachfragen, ob Du die Offerte schon anschauen konntest.
      
      Falls es diesbezüglich Unklarheiten oder Änderungswünsche gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",fdrafol"
    form: |
      Bonjour [[Name]]  
      
      Je voulais vous demander si vous aviez déjà pu consulter l'offre.
      S'il y a des incertitudes ou des demandes de modification, je serai ravi*e de vous aider.
      
      Meilleures salutations
      {{firstname}}
      
  - trigger: ",drafo2"
    form: |
      Guten Tag [[Name]]  
      
      Ich wollte mich erkundigen, ob noch Interesse an unserem Angebot besteht.
      Andernfalls wird die Offerte demnächst ihre Gültigkeit verlieren. 
      
      Falls es diesbezüglich Unklarheiten oder Änderungswünschen gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",fdrafo2"
    form: |
      Bonjour [[Name]]  
      
      Je voulais vous demander s'il y avait encore de l'intérêt pour notre offre.
      Dans le cas contraire, l'offre perdra prochainement sa validité. 
      
      S'il y a des ambiguïtés ou des demandes de modification à ce sujet, je serai ravi*e de vous aider.
      
      Meilleures salutations
      {{firstname}}
    
  - trigger: ",abs"
    form: |
      Guten Tag [[Name]]  
      
      Besten Dank für die Rückmeldung.
      Wir hoffen ein anders Mal behilflich sein zu können.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",fabs"
    form: |
      Bonjour [[Name]]
      
      Nous vous remercions pour l'information concernant l'annulation.
      Nous serons ravi*e*s de vous aider une autre fois.
      
      Meilleures salutations
      {{firstname}}
      
  - trigger: ",anu"
    form: |
      Guten Tag [[Name]]  
      
      Da wir keine Rückmeldung erhalten haben, haben wir die Anfrage annulliert.
      Wir hoffen ein anders Mal behilflich sein zu können.
      
      Freundliche Grüsse
      {{firstname}}
            
  - trigger: ",fanu"
    form: |
      Bonjour [[Name]]  
      
      Comme nous n'avons pas reçu de réponse, nous avons annulé la demande.
      Nous serons ravi*e*s de vous aider une autre fois.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",kur"
    form: |
      Guten Tag [[Name]]
      
      Hier findest Du unser Kurier Formular: https://forms.gle/MxVA6MxyYRwKpfy28
      Sobald Du dieses ausgefüllt und den Vertrag digital unterzeichnet hast (separate Mail), wird Deine Anfrage an den Kurier weitergeleitet.
      
      Bei Fragen oder Änderungswünschen stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",fkur"
    form: |
      Bonjour [[Name]]
      
      Vous trouverez ici notre formulaire de courrier : https://forms.gle/MxVA6MxyYRwKpfy28
      Dès que vous l'aurez rempli et que vous aurez signé le contrat (mail séparé), votre demande sera transmise au courrier.
      
      Je reste à votre disposition pour toute question ou demande de modification.
      
      Meilleures salutations
      {{firstname}}
      
  - trigger: ",audio"
    form: |
      Guten Tag [[Name]]
      
      Herzlichen Dank für Deine Anfrage. 
      Wir haben für die verschiedenen Audioanschlüsse eine separate Anleitung vorbereitet, die Du unter folgendem Link abrufen kannst: [https://manuals.rentshop.ch/audio-anschluesse/].
      Falls weitere Fragen auftauchen, stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",faudio"
    form: |
      Bonjour [[Name]]
      
      Nous vous remercions pour votre demande. 
      Nous avons préparé des instructions séparées pour les différentes connexions audio, que vous pouvez consulter en cliquant sur le lien suivant : [https://manuals.rentshop.ch/audio-anschluesse/].
      Si d'autres questions se posent, je suis à votre disposition.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",bar"
    replace: "Bar bezahlt"
    
  - trigger: ",karte"
    replace: "Mit Karte bezahlt"
    
  - trigger: ",twint"
    replace: "Mit Twint bezahlt"   
        
  - trigger: ",tel"
    replace: "Anfrage per Telefon"
        
  - trigger: ",rech"
    replace: "Zahlt auf Rechnung"
    
 

