imports:
  - "sub/_tawk.yml"
  - "sub/_generator.yml"

matches:
  - trigger: ",fg"
    replace: |
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",ok"
    form: |
      Guten Tag [[Name]]
      
      Gib mir doch bitte eine kurze Rückbestätigung, dass Du mit der Reservation und den Bedingungen einverstanden bist.
      
      Bei Fragen stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}
  - trigger: ",dank"
    form: |
      Guten Tag [[Name]]  
      
      Super, besten Dank für die Bestätigung.  
      
      Bei Fragen stehe ich gerne zur Verfügung.  
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",drafol"
    form: |
      Guten Tag [[Name]]  
      
      Ich wollte kurz nachfragen, ob du die Offerte schon anschauen konntest. 
      Falls es diesbezüglich Unklarheiten oder Änderungswünsche gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",drafol2"
    form: |
      Guten Tag [[Name]]  
      
      Ich wollte mich erkundigen, ob noch Interesse an unserem Angebot besteht? 
      Anderenfalls wird die Offerte demnächst ihre Gültigkeit verlieren. 
      Falls es diesbezüglich Unklarheiten oder Änderungswünschen gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
    
  - trigger: ",abs"
    form: |
      Guten Tag [[Name]]  
      
      Besten Dank für die Rückmeldung.
      Wir hoffen ein anders Mal behilflich sein zu können und wünschen eine guten Event.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",anu"
    form: |
      Guten Tag [[Name]]  
      
      Da wir keine Rückmeldung erhalten haben, haben wir den Auftrag annulliert.
      Wir hoffen, dass wir dich bei deinem nächsten Event unterstützen können.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",frag"
    form: |
      Bei Fragen stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",anf"
    form: |
      Guten Tag [[Name]]  
      
      Besten Dank für die Anfrage.
      
  - trigger: ",chat"
    form: |
      Guten Tag [[Name]]  
      
      Besten Dank für deine Anfrage im Chat.
      
  - trigger: ",rück"
    form: |
      Guten Tag [[Name]]  
      
      Besten Dank für die Rückmeldung.
       
  - trigger: ",sumup"
    replace: "Mit Karte bezahlt"
    
  - trigger: ",depot"
    replace: "Bitte beachte, dass während der Miete ein Depot hinterlegt werden muss."
    
  - trigger: ",tel"
    replace: "Anfrage per Telefon"
    
  - trigger: ",track"
    form: "http://www.post.ch/swisspost-tracking?formattedParcelCodes=99.60.096403.0000[[Nummer]]&p_language=de"   
    
  - trigger: ",fehlt"
    replace: "Für die Bestätigung der Offerte, benötige ich noch deine Adresse und die Natelnummer."
    
  - trigger: ",dring"
    replace: "Bitte sende uns den Vertrag bis 14:00 Uhr zurück, damit wir die Ware rechtzeitig verschicken können."
    
  - trigger: ",tawk"
    replace: "Damit ich dir eine Offerte zustellen kann, benötige ich noch deinen Namen, Adresse, Natelnummer und E-Mail Adresse."
    
  - trigger: ",rech"
    replace: "Zahlt auf Rechnung"
    
  - trigger: ",frag"
    replace: "Bei Fragen oder Änderungswünschen stehe ich gerne zur Verfügung."    
    
  - trigger: ",lagzh"
    replace: "Das Lager Zürich hat unter der Woche täglich von 11.00 -17.00 Uhr geöffnet. Am Donnerstag kann auf Anfrage bis um 19.00 Uhr abgeholt werden."
    
  - trigger: ",lagbs"
    replace: "Das Lager Basel hat jeweils am Mittwoch von 18:00 - 19:30 Uhr geöffnet."  
    
  - trigger: ",lagbe"
    replace: "Das Lager Bern hat jeweils am Mittwoch von 16:30-19:00 Uhr geöffnet. Falls dir die Zeiten nicht passen, haben wir in Bern auch ein Pickup Lager (ohne Betreuung), bei welchem du jederzeit dein Equipment abholen und returnieren kannst. Bitte lass mich es wissen, falls du lieber auf Pickup wechseln möchtest."
    
