imports:
  - "sub/_tawk.yml"
  - "sub/_generator.yml"
  - "sub/_struggler.yml"

matches:
  - trigger: ",bar"
    replace: "Bar bezahlt"
    
  - trigger: ",karte"
    replace: "Mit Karte bezahlt"
    
  - trigger: ",twint"
    replace: "Mit Twint bezahlt"   
        
  - trigger: ",tel"
    replace: "Anfrage per Telefon"
        
  - trigger: ",rech"
    replace: "Zahlt auf Rechnung"
    
  - trigger: ",fg"
    replace: |
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",ffg"
    replace: |
      Meilleures salutations
      {{firstname}}

  - trigger: ",ok"
    form: |
      Guten Tag [[Name]]
      
      Ich wollte kurz nachfragen, ob du die Bestätigung schon anschauen konntest. 
      Gib mir doch bitte eine kurze Rückbestätigung, dass Du mit der Reservation und den Bedingungen einverstanden bist.
      
      Bei Fragen stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",fok"
    form: |
      Bonjour [[Name]]
      
      Je voulais vous demander si vous aviez déjà pu jeter un coup d'œil à la confirmation. 
      Je vous invite à me confirmer brièvement que vous êtes d'accord avec la réservation et les conditions.
      
      Je suis à votre disposition pour toute question.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",dank"
    form: |
      Guten Tag [[Name]]  
      
      Super, besten Dank für die Bestätigung.  
      
      Bei Fragen stehe ich gerne zur Verfügung.  
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",fdank"
    form: |
      Bonjour [[Name]]  
      
      Super, merci beaucoup pour la confirmation.  
      
      Je suis à votre disposition pour toute question.  
      
      Meilleures salutations
      {{firstname}}
  
  - trigger: ",vert"
    form: |
      Guten Tag [[Name]]  
      
      Ich wollte kurz nachfragen, ob du den Mietvertrag (E-Mail von e-Signature) schon anschauen konntest. 
      
      Falls es diesbezüglich Unklarheiten oder Änderungswünsche gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
  
  - trigger: ",fvert"
    form: |
      Bonjour [[Name]]  
      
      Je voulais vous demander si vous aviez déjà pu consulter le contrat de location (e-mail d'e-Signature). 
      
      S'il y a des imprécisions ou des demandes de modification à ce sujet, je serai ravi de vous aider.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",dring"
    form: |
      Guten Tag [[Name]]  

      Besten Dank für die Anfrage.
      Ich habe soebenen den Mietvertrag zugestellt (siehe E-Mail von e-Signature).
      Damit die Buchung Heute verschickt werden kann, muss der Vertrag bis um 14.00 Uhr unterschrieben werden.
      
      Falls es diesbezüglich Unklarheiten oder Änderungswünsche gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
        
  - trigger: ",fdring"
    form: |
      Bonjour [[Name]] 
      
      Merci pour votre demande.
      Je viens de vous envoyer le contrat de location (voir e-mail d'e-Signature).
      Merci de nous renvoyer le contrat avant 14h00 afin que nous puissions envoyer la marchandise à temps.
      
      S'il y a des ambiguïtés ou des modifications à ce sujet, je serai ravi de vous aider.
      
      Meilleures salutations 
      {{firstname}}

  - trigger: ",drafol"
    form: |
      Guten Tag [[Name]]  
      
      Ich wollte kurz nachfragen, ob du die Offerte schon anschauen konntest. 
      
      Falls es diesbezüglich Unklarheiten oder Änderungswünsche gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",fdrafol"
    form: |
      Bonjour [[Name]]  
      
      Je voulais savoir si vous aviez déjà pu consulter l'offre. 
      S'il y a des incertitudes ou des demandes de modification, je serai ravi de vous aider.
      
      Meilleures salutations
      {{firstname}}
      
  - trigger: ",drafo2"
    form: |
      Guten Tag [[Name]]  
      
      Ich wollte mich erkundigen, ob noch Interesse an unserem Angebot besteht? 
      Andernfalls wird die Offerte demnächst ihre Gültigkeit verlieren. 
      
      Falls es diesbezüglich Unklarheiten oder Änderungswünschen gibt, helfe ich gerne weiter.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",fdrafo2"
    form: |
      Bonjour [[Name]]  
      
      Je voulais savoir s'il y avait encore de l'intérêt pour notre offre ? 
      Dans le cas contraire, l'offre perdra prochainement sa validité. 
      
      S'il y a des ambiguïtés ou des demandes de modification à ce sujet, je serai ravi de vous aider.
      
      Meilleures salutations
      {{firstname}}
    
  - trigger: ",abs"
    form: |
      Guten Tag [[Name]]  
      
      Besten Dank für die Rückmeldung.
      Wir hoffen ein anders Mal behilflich sein zu können.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",fabs"
    form: |
      Bonjour [[Name]]
      
      Nous vous remercions pour l'information concernant l'annulation.
      Nous serons ravis de vous aider une autre fois.
      
      Meilleures salutations
      {{firstname}}
      
  - trigger: ",anu"
    form: |
      Guten Tag [[Name]]  
      
      Da wir keine Rückmeldung erhalten haben, haben wir die Anfrage annulliert.
      Wir hoffen ein anders Mal behilflich sein zu können.
      
      Freundliche Grüsse
      {{firstname}}
            
  - trigger: ",fanu"
    form: |
      Bonjour [[Name]]  
      
      Comme nous n'avons pas reçu de réponse, nous avons annulé la demande.
      Nous serons ravis de vous aider une autre fois.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",redep"
    form: |
      Guten Tag [[Name]]  
      
      Deine Buchung ist zurückgekommen - besten Dank.
      Damit wir das Depot zurückerstatten können, benötige ich noch Deine IBAN.
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",fredep"
    form: |
      Bonjour [[Name]]  
      
      Votre commande est de retour - merci beaucoup.
      Pour que nous puissions vous rembourser le dépôt, j'ai besoin de votre IBAN.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",ruck"
    form: |
      Guten Tag [[Name]]  
      
      Besten Dank für die Rückmeldung.

  - trigger: ",fruck"
    form: |
      Bonjour [[Name]]  
      
      Merci pour votre réponse.

  - trigger: ",anf"
    replace: "Guten Tag Besten Dank für die Anfrage."
    
  - trigger: ",fanf"
    replace: "Bonjour Nous vous remercions de votre demande."

  - trigger: ",handy"
    replace: "Damit ich den Mietvertrag zustellen kann, benötige ich noch eine Handynummer. Der Mietvertrag wird per SMS Code unterschrieben."

  - trigger: ",depot"
    replace: "Bitte beachte, dass während der Miete ein Depot hinterlegt werden muss."
    
  - trigger: ",track"
    form: "http://www.post.ch/swisspost-tracking?formattedParcelCodes=99.60.096403.0000[[Nummer]]&p_language=de"   
    
  - trigger: ",fehlt"
    replace: "Für die Bestätigung der Offerte, benötige ich noch deine Adresse und die Natelnummer."
    
  - trigger: ",ofer"
    replace: "Damit ich dir eine Offerte zustellen kann, benötige ich noch deinen Namen, Adresse, Natelnummer und E-Mail Adresse."
    
  - trigger: ",frag"
    replace: "Bei Fragen oder Änderungswünschen stehe ich gerne zur Verfügung."    
    
  - trigger: ",lagzh"
    replace: "Das Lager Zürich hat unter der Woche täglich von 11.00 -17.00 Uhr geöffnet. Am Donnerstag kann auf Anfrage bis um 19.00 Uhr abgeholt werden."
    
  - trigger: ",lagbs"
    replace: "Das Lager Basel hat jeweils am Mittwoch von 18:00 - 19:30 Uhr geöffnet."  
    
  - trigger: ",lagbe"
    replace: "Das Lager Bern hat jeweils am Mittwoch von 17:00-19:00 Uhr geöffnet. Falls dir die Zeiten nicht passen, haben wir in Bern auch ein Pickup Lager (ohne Betreuung), bei welchem du jederzeit dein Equipment abholen und returnieren kannst. Bitte lass mich es wissen, falls du lieber auf Pickup wechseln möchtest."
      
  - trigger: ",int"
    form: |
      Bonjour [[Name]]  
      
      Je voulais savoir s'il y avait encore de l'intérêt pour notre offre ? 
      Dans le cas contraire, l'offre perdra prochainement sa validité. 
      S'il y a des incertitudes ou des souhaits de modification à ce sujet, je vous aiderai volontiers.
      
      Meilleures salutations
      {{firstname}}

  - trigger: ",port"
    form: |
      Bonjour [[Name]]  
      
      Pour pouvoir envoyer le contrat de location, j'ai besoin d'un numéro de téléphone portable suisse. 
      Le contrat de location sera signé par code SMS.
      
      Meilleures salutations
      {{firstname}}
      
  - trigger: ",kur"
    form: |
      Guten Tag [[Name]]
      
      Hier findest Du unser Kurier Formular: https://forms.gle/MxVA6MxyYRwKpfy28
      Sobald du dieses ausgefüllt und den Vertrag digital unterzeichnet hast (separate Mail), wird Deine Anfrage an den Kurier weitergeleitet.
      
      Bei Fragen oder Änderungswünschen stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}
      
  - trigger: ",audio"
    form: |
      Guten Tag [[Name]]
      
      Herzlichen Dank für Deine Anfrage. 
      Wir haben für die verschiedenen Audioanschlüsse eine separate Anleitung vorbereitet, die du unter folgendem Link abrufen kannst: [https://manuals.rentshop.ch/audio-anschluesse/].
      Falls weitere Fragen auftauchen, stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}
 

