imports:
  - "sub/_tawk.yml"
  - "sub/_generator.yml"

matches:

  - trigger: ",ok"
    form: |
      Guten Tag [[Name]]
      
      Gib mir doch bitte eine kurze Rückbestätigung, dass Du mit der Reservation und den Bedingungen einverstanden bist.
      
      Bei Fragen stehe ich gerne zur Verfügung.
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",dank"
    form: |
      Guten Tag [[Name]]  
      
      Super, besten Dank für die Bestätigung.  
      
      Bei Fragen stehe ich gerne zur Verfügung.  
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",drafol"
    form: |
      Guten Tag [[Name]]  
      
      Blafdlafjsd
      
      Freundliche Grüsse
      {{firstname}}

  - trigger: ",sumup"
    replace: "Mit Karte bezahlt"
